import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {JSX, Suspense} from "react";
import "./globals.css";
import {AudioProvider} from "@/context/AudioContext";
import {GuestProvider} from "@/context/GuestContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <Suspense fallback={<div>Cargando...</div>}>
          <AudioProvider>
              <GuestProvider>{children}</GuestProvider>
          </AudioProvider>
      </Suspense>
      </body>
    </html>
  );
}
